### ISSUE TITLE
D3D9Client intergation to Orbiter core

### ISSUE THREAD

**Issue by jarmonik** [orbitersim/orbiter#139]
How do we proceed with the integration of D3D9Client into the Orbiter core ? We did discuss about this "briefly" right after Open Orbiter announcement. I have moved the float based vector math operations (i.e. FVECTOR) into the DrawAPI.h also the advanced SketchPad interface has been integrated to the base interface in DrawAPI.h. I have tested that this should be backwards compatible with the Orbiter 2016 based MFDs when using D3D9 and inline DX7. Of course, any "new" add-on using the advanced parts of the interface won't work in DX7

I have also added oapiLoadSurfaceEx() function into the API and realized later on that there are no implementation of it on DX7 side even if the function exists in GraphicsClient base class. I have no idea on how to implement it on DX7, might not be possible at all.

There are some other minor additions and fixes such as removal of over-lapping enums FontStyle and Font::Style. I have also made modifications to CMake files to get a proper set of visual studio project files and having the compiled binaries in a right place in a build dir (of course, the "right" place is a matter of taste). I don't know if these modifications conflict with the Ninja build style. 

I probably should move the source codes from OrbiterSDK/D3D9Client to OVP/D3D9Client

**Comment by mschweiger** [comment]
Thanks for looking into this! I have sent you an invitation to join the orbitersim team so you can get access to the orbitersim/orbiter repository, which should make it easier for you to work on the D3D9Client integration without having to wait for me to merge any pull requests.

I would suggest to keep the D3D9Client integration work on a separate feature branch off the main branch for now until all is working properly.

As I mentioned a few times on the forum, I want to publish one more "compatibility" release with a 32-bit build that includes the built-in DX7 client. I'll leave it to you to decide if you want the D3D9Client to be included in that release. If so, the release would happen _after_ the D3D9Client branch has been merged into main. Otherwise, I'll continue finalising the release based on the current main, and we'll keep the D3D9Client branch separate until _after_ the release.

After that release, I'll clean out the built-in client and external D3D7Client, and switch to an x64-build only. At that point, it will become essential to have the D3D9Client integrated and ready to take over.

Moving the client sources from OrbiterSDK/D3D9Client to OVP/D3D9Client sounds good to me. I could also rename "OVP" to "Graphics" in analogy to the "Sound" directory for the sound subsystem. "OVP" is a bit of an anachronism now that the entire code is open-source.

I'll be away on holiday for the next two weeks and may not be able to do a lot on the repository. But at least I hope to be able to get a few remaining tasks towards the release done so we can get that out of the way soon.

**Comment by jarmonik** [comment]
Thanks for the invitation. Yes, it would make sense to include the D3D9Client into the Orbiter x86 build since, it's reasonably well backwards and forward compatible. The DX9 is starting to get old and Vulkan would be the next logical step forward. It's going to take some time to build it and during that time add-on developers can start preparing by moving GDI stuff on a Sketchpad, which will be the same on Vulkan as it is on DX9.

Have a nice holiday.
