### ISSUE TITLE
Discord community for Orbiter

### ISSUE THREAD

**Issue by uranuspucksaxophone** [orbitersim/orbiter#171]
Discord is very bad compared to Element, but, many people use it so it would be nice to have a Discord community too, in addition to an Element community, my suggestion is by setting up an Element to Discord bridge.

Related to PR #170

**Comment by supersonic71** [comment]
I agree, a bridge would be nice. 
There is already a discord community, but it requires 10 forum posts to join, which imo is a barrier to entry for new comers. https://github.com/orbitersim/orbiter/issues/9
I would be grateful if the 10 forum post requirement was relaxed.

**Comment by JDat** [comment]
Why I need another animal in modern messing zoo? I already registered in ton of modern social messing tools. Should I need to keep open on my computer all of them? It is like 20 different messengers/communicators at the same time. And now there somebody advice to add  another just because he like it and it is have ONE nice feature. Why we can not live with as less ass possible communication methods? Discord + Orbiter forum is enough.
