### ISSUE TITLE
tilelabel render bug

### ISSUE THREAD

**Issue by spacex15** [orbitersim/orbiter#260]
in TileLabel::Render  (tilelabel.cpp)

the active local variable is not initialized (both for inline and d3d9client)

Running in visual studio debug mode
if you start the shuttle-A ISS approach scenario with surface markers enabled
switch to external view and move your mouse around

you'll get a crash telling that active is being used without beiing initialized

**Comment by mschweiger** [comment]
Thanks for the catch. I'll fix it, but since I can't reproduce the exception, it would help if you could provide a bit of additional information to figure out why it triggers for you:

After your debugger triggers the exception, can you check the values of

```
renderlabel[i].label
renderlabel[i].labeltype
```

Also could you check if your Config\Earth\Label.cfg contains an entry for that labeltype.

**Comment by spacex15** [comment]
yes you're right 
it was caused by a conflict with nassp addon added labels in my textures earth directory
example B 12.562 109.433 0.000 Mui Ganh (354) in Textures\Earth\Label\04\000000
and missing label type B in the standard orbiter label.cfg
