### ISSUE TITLE
Drop D3D7Client

### ISSUE THREAD

**Issue by dimitry-ishenko** [orbitersim/orbiter#344]
With the D3D9Client now being part of the project, does it make sense to drop the old D3D7Client?

**Comment by n7275** [comment]
I am not sure I would agree with dropping it at the moment, mostly because it is a good demo of a very simple GraphicsClient class implementation. If you are going to do anything related to DX7, it should probably be to finish the work of making the Orbite core code no longer depend on anything related to DX7. (Maybe this has already been done? I know Dr. @mschweiger wanted to do this back in 2020).

**Comment by dimitry-ishenko** [comment]
@n7275 well it can be parked in a separate branch that people will be able to refer to. Going forward the D3D9Client seems to be the chosen one.

In some distant future I would like to try to pair it with the DXVK library so we can have a Linux version of Orbiter. But this will have to be preceded by numerous clean-ups to make the codebase cross-platform.

I don't mind looking decoupling the core code from DX7. Maybe @mschweiger can chime in (I know, wishful thinking 😉 ) and let us know if he's already done any work on this?

**Comment by dimitry-ishenko** [comment]
While we are on the subject:

* The tileedit utility can/should be spun off into it's own project and removed from Orbiter. @mschweiger already has it as a separate repo [here](https://github.com/mschweiger/orbiter-tileedit).

* There are a few other things in the Utils dir, which seems like they can be in their own projects.

**Comment by n7275** [comment]
It might be worth jumping into Orbiter Discord/Orbiter-Forum for a quick discussion.

**Comment by dimitry-ishenko** [comment]
@n7275 joining discord now

**Comment by dimitry-ishenko** [comment]
As discussed in the forums, D3D7 client which incidentally is *not* the same as the built-in client, is still being used. So, closing for now.
