### ISSUE TITLE
Gravity Model file missing/typo?

### ISSUE THREAD

**Issue by GLS-SSV** [orbitersim/orbiter#399]
I'm getting this error during loading:
_000006.141: Module Mars.dll .............. [Build 231227, API 231227]
000006.146: GRAVITY MODEL ERROR: COEFFICIENT FILE GravityModels\jgmro_120f_sha.tab NOT FOUND_

The file included in the package is "jgmro_120d_sha.tab", which also doesn't match with the contents of the file "Notes on Gravity Models.txt".

Using the latest auto-build x86 package. (I didn't any thing else yet due to lack of time)

**Comment by n7275** [comment]
That's really odd. Especially since I know for an absolute fact that I had 120f, and tested it, and at least a few others have as well. There are graphs on the forum of data collected from mars. Yet the commit history doesn't show where anything has ever changed since my initial commits 2 years ago.

Either way, its a very easy fix, I just need to download the correct model from here https://ode.rsl.wustl.edu/mars/DataSetExplorer.aspx?target=mars&instrumenthost=MRO&instrumentid=RSS&datasetid=MRO-M-RSS-5-SDP-V1.0&volumeid=MRORS_1XXX&pathtovol=data/shadr/ and commit it.

I suppose it's possible that I had a local copy of 120f that was living in my out/Install/... folder, that made it so it worked?
