### ISSUE TITLE
Hover Engine Glass Cockpit Indicator is Backwards in Fullscreen 2560x1080

### ISSUE THREAD

**Issue by n7275** [orbitersim/orbiter#464]
![image](https://github.com/orbitersim/orbiter/assets/100335/b9cd7c2a-63ff-4b75-ab23-f656d3857df9)

![image](https://github.com/orbitersim/orbiter/assets/100335/a1d29135-9c7f-49b2-abeb-c7b1dbc9b1f1)

**Comment by n7275** [comment]
This issue is also present as far back as the Orbiter 2016 d3d9 client. Not a new issue, I'm just noticing it now.

**Comment by TheGondos** [comment]
In defpanel.cpp there might be something :
```
	// Update hover engine status
	vofs += 4;
	if (g_focusobj->NumThrusters(THGROUP_HOVER)) {
		th = g_focusobj->GetThrusterGroupLevel (THGROUP_HOVER);
		if (th != enghovr) {
			enghovr = th;
			grp->Vtx[vofs+1].x = grp->Vtx[vofs+3].x = (float)((46.0+enghovr*94.0)*scale+gapw);
		}
	}
```
The '+gapw' is not done when drawing other statuses (fuel/main engine) and seems related to the gap width between MFD buttons.
Not sure it has something to do with the hover engine status...
Maybe you can try to remove it and see what happens? (I cannot reproduce the issue because my monitor won't do more than 1920x1080)

**Comment by n7275** [comment]
I'll test it out.

**Comment by n7275** [comment]
removing the "gapw" and adding a "dx+" fixed the issue.

PR is up #468
