### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by dimitry-ishenko** [orbitersim/orbiter#473]
It seems like a waste of electrons to make nightly builds when commits come around once every couple of weeks. 

@DarkWanderer is there a reason you've added them? on-push should be sufficient. Or maybe there is a way to skip nightly build if there were no commits for the day?

**Comment by DarkWanderer** [comment]
Yes, there is a reason. In proper software engineering, things are built having the target state in mind - active development - rather than prematurely optimising for the status quo.

Nightly builds normally contain more runs than just same as on push, for example address sanitizer runs, matrix runs against multiple compulers, extended tests etc. If you are concerned about extra runs, feel free to add optimisation which skips the run if the last commit time was >24h ago

**Comment by dimitry-ishenko** [comment]
"proper software engineering", "target state", "active development"...

Those are all very nice hyperboles, but in reality you are putting the cart waaaaaay before the horse. :) Those extra runs don't come for free... well, maybe to you and me they do, but in general somebody has to pay for them. We often like to talk about sustainability, climate change, etc. but I wish our actions were more reflective of our views...

I am not saying what you did is bad. But, it just seems way too premature.
