### ISSUE TITLE
D3d9 , D3d7client and Internal Graphics broken (deleting  and recreating meshes no longer display properly)

### ISSUE THREAD

**Issue by spacex15** [orbitersim/orbiter#89]
See my comment here
The Dx9 client is also broken

https://github.com/orbitersim/orbiter/commit/f49880790620d414b7ff963eeb5b30cea76f17f2?_pjax=%23js-repo-pjax-container#commitcomment-55016624

**Comment by jarmonik** [comment]
But of course ((DWORD_PTR)-1) should do equally well.

**Comment by mschweiger** [comment]
I don't really want to propagate the DWORD_PTR, UINT_PTR etc. changes further than required, i.e. where they might stand in for pointers. Otherwise we might end up changing nearly all integer types throughout the API. So where an integer is just meant to represent an index, it should be possible to stick to UINT for both 32 and 64 bit. In which case (UINT)-1 should remain valid.
What do you think?

Did my edits in branch #89 fix the original problem, or is this still present due to (UINT)-1 problems anywhere? Any specific instances?

**Comment by jarmonik** [comment]
The (UINT)-1 should be fine since so-far it's only used as an index. Since the code is already using UINT -1 then let's stay with that. I am not aware of any problems with it.

**Comment by mschweiger** [comment]
@spacex15 : Could you check if the problems you found are fixed in 6cf7710 ?

**Comment by spacex15** [comment]
Yes your https://github.com/orbitersim/orbiter/tree/89-graphicsclient_pointer_mismatch branch fixes the problem

You are go for merge

Thanks
